/*
 * This file is generated by jOOQ.
*/
package com.dreamer.pojo.po;


import lombok.Data;

import java.sql.Timestamp;


/**
 * 日志表
 */
@Data
public class SysLogPojo extends AbstractBasePojo {

    private static final long serialVersionUID = 2129002071;

    private Long id;
    private String moduleName;
    private String moduleDesc;
    private String remoteAddr;
    private Long operateId;
    private String operateName;
    private String operateMethod;
    private String requestUrl;
    private String params;
    private String result;
    private String exception;
    private Timestamp operateTime;

}
