/*
 * This file is generated by jOOQ.
*/
package com.dreamer.domain.tables;


import com.dreamer.domain.Dreamer;
import com.dreamer.domain.Keys;
import com.dreamer.domain.tables.records.WcSessionTokenRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * 微信会话token表
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class WcSessionToken extends TableImpl<WcSessionTokenRecord> {

    /**
     * The reference instance of <code>dreamer.wc_session_token</code>
     */
    public static final WcSessionToken WC_SESSION_TOKEN = new WcSessionToken();
    private static final long serialVersionUID = -1590019661;
    /**
     * The column <code>dreamer.wc_session_token.id</code>. 主键
     */
    public final TableField<WcSessionTokenRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "主键");
    /**
     * The column <code>dreamer.wc_session_token.session_token</code>. 平台会话token
     */
    public final TableField<WcSessionTokenRecord, String> SESSION_TOKEN = createField("session_token", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "平台会话token");
    /**
     * The column <code>dreamer.wc_session_token.open_id</code>. 微信用户唯一标识
     */
    public final TableField<WcSessionTokenRecord, String> OPEN_ID = createField("open_id", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "微信用户唯一标识");
    /**
     * The column <code>dreamer.wc_session_token.session_key</code>. 微信会话密钥
     */
    public final TableField<WcSessionTokenRecord, String> SESSION_KEY = createField("session_key", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "微信会话密钥");
    /**
     * The column <code>dreamer.wc_session_token.create_time</code>. 创建时间
     */
    public final TableField<WcSessionTokenRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");

    /**
     * Create a <code>dreamer.wc_session_token</code> table reference
     */
    public WcSessionToken() {
        this("wc_session_token", null);
    }

    /**
     * Create an aliased <code>dreamer.wc_session_token</code> table reference
     */
    public WcSessionToken(String alias) {
        this(alias, WC_SESSION_TOKEN);
    }

    private WcSessionToken(String alias, Table<WcSessionTokenRecord> aliased) {
        this(alias, aliased, null);
    }

    private WcSessionToken(String alias, Table<WcSessionTokenRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "微信会话token表");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WcSessionTokenRecord> getRecordType() {
        return WcSessionTokenRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dreamer.DREAMER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<WcSessionTokenRecord, Long> getIdentity() {
        return Keys.IDENTITY_WC_SESSION_TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<WcSessionTokenRecord> getPrimaryKey() {
        return Keys.KEY_WC_SESSION_TOKEN_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<WcSessionTokenRecord>> getKeys() {
        return Arrays.<UniqueKey<WcSessionTokenRecord>>asList(Keys.KEY_WC_SESSION_TOKEN_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WcSessionToken as(String alias) {
        return new WcSessionToken(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WcSessionToken rename(String name) {
        return new WcSessionToken(name, null);
    }
}
