/*
 * This file is generated by jOOQ.
*/
package com.dreamer.pojo;


import com.dreamer.domain.enums.SysMenuStatus;
import com.dreamer.domain.enums.SysMenuType;
import lombok.Data;

import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * 菜单表
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.4"
        },
        comments = "This class is generated by jOOQ"
)
@Data
public class SysMenuPojo implements Serializable {

    private static final long serialVersionUID = -466337487;

    private Long id;
    private Long parentId;
    private SysMenuType type;
    private String name;
    private String href;
    private String target;
    private String icon;
    private Integer sort;
    private SysMenuStatus status;
    private String permission;
    private Timestamp createAt;
    private Timestamp updateAt;
    private String remarks;
    private Boolean delFlag;
    private Long version;

}
