/*
 * This file is generated by jOOQ.
*/
package com.dreamer.pojo;


import lombok.Data;

import java.io.Serializable;
import java.sql.Timestamp;


/**
 * 角色表
 */
@Data
public class SysRolePojo implements Serializable {

    private static final long serialVersionUID = -1100170357;

    private Long id;
    private String name;
    private String createBy;
    private Timestamp createAt;
    private String updateBy;
    private Timestamp updateAt;
    private String remarks;
    private Boolean delFlag;

}
