/*
 * This file is generated by jOOQ.
*/
package com.dreamer.pojo;


import lombok.Data;

import javax.annotation.Generated;
import java.io.Serializable;


/**
 * 角色-菜单
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.4"
        },
        comments = "This class is generated by jOOQ"
)
@Data
public class SysRoleMenuPojo implements Serializable {

    private static final long serialVersionUID = 1753572126;

    private Long id;
    private Long sysRoleId;
    private Long sysMenuId;

}
