/*
 * This file is generated by jOOQ.
*/
package com.dreamer.pojo;


import lombok.Data;

import java.io.Serializable;


/**
 * 用户-角色
 */
@Data
public class SysUserRolePojo implements Serializable {

    private static final long serialVersionUID = -687766676;

    private Long id;
    private Long sysUserId;
    private Long sysRoleId;

}
