/*
 * This file is generated by jOOQ.
*/
package com.dreamer.domain;


import com.dreamer.domain.tables.*;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Dreamer extends SchemaImpl {

    /**
     * The reference instance of <code>dreamer</code>
     */
    public static final Dreamer DREAMER = new Dreamer();
    private static final long serialVersionUID = 1239521014;
    /**
     * 字典表
     */
    public final SysDict SYS_DICT = com.dreamer.domain.tables.SysDict.SYS_DICT;

    /**
     * 日志表
     */
    public final SysLog SYS_LOG = com.dreamer.domain.tables.SysLog.SYS_LOG;

    /**
     * 菜单表
     */
    public final SysMenu SYS_MENU = com.dreamer.domain.tables.SysMenu.SYS_MENU;

    /**
     * 角色表
     */
    public final SysRole SYS_ROLE = com.dreamer.domain.tables.SysRole.SYS_ROLE;

    /**
     * 角色-菜单
     */
    public final SysRoleMenu SYS_ROLE_MENU = com.dreamer.domain.tables.SysRoleMenu.SYS_ROLE_MENU;

    /**
     * 用户表
     */
    public final SysUser SYS_USER = com.dreamer.domain.tables.SysUser.SYS_USER;

    /**
     * 用户-角色
     */
    public final SysUserRole SYS_USER_ROLE = com.dreamer.domain.tables.SysUserRole.SYS_USER_ROLE;

    /**
     * No further instances allowed
     */
    private Dreamer() {
        super("dreamer", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
                SysDict.SYS_DICT,
                SysLog.SYS_LOG,
                SysMenu.SYS_MENU,
                SysRole.SYS_ROLE,
                SysRoleMenu.SYS_ROLE_MENU,
                SysUser.SYS_USER,
                SysUserRole.SYS_USER_ROLE);
    }
}
