/*
 * This file is generated by jOOQ.
*/
package com.dreamer.domain.tables.pojos;


import com.dreamer.domain.enums.SysDictStatus;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 字典表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysDictPojo implements Serializable {

    private static final long serialVersionUID = -494057948;

    private Long          id;
    private String        label;
    private String        groupName;
    private String        key;
    private String        value;
    private String        description;
    private Integer       sort;
    private SysDictStatus status;
    private Timestamp     createAt;
    private Timestamp     updateAt;
    private String        remarks;
    private Boolean       delFlag;
    private Long          version;

    public SysDictPojo() {}

    public SysDictPojo(SysDictPojo value) {
        this.id = value.id;
        this.label = value.label;
        this.groupName = value.groupName;
        this.key = value.key;
        this.value = value.value;
        this.description = value.description;
        this.sort = value.sort;
        this.status = value.status;
        this.createAt = value.createAt;
        this.updateAt = value.updateAt;
        this.remarks = value.remarks;
        this.delFlag = value.delFlag;
        this.version = value.version;
    }

    public SysDictPojo(
        Long          id,
        String        label,
        String        groupName,
        String        key,
        String        value,
        String        description,
        Integer       sort,
        SysDictStatus status,
        Timestamp     createAt,
        Timestamp     updateAt,
        String        remarks,
        Boolean       delFlag,
        Long          version
    ) {
        this.id = id;
        this.label = label;
        this.groupName = groupName;
        this.key = key;
        this.value = value;
        this.description = description;
        this.sort = sort;
        this.status = status;
        this.createAt = createAt;
        this.updateAt = updateAt;
        this.remarks = remarks;
        this.delFlag = delFlag;
        this.version = version;
    }

    public Long getId() {
        return this.id;
    }

    public SysDictPojo setId(Long id) {
        this.id = id;
        return this;
    }

    public String getLabel() {
        return this.label;
    }

    public SysDictPojo setLabel(String label) {
        this.label = label;
        return this;
    }

    public String getGroupName() {
        return this.groupName;
    }

    public SysDictPojo setGroupName(String groupName) {
        this.groupName = groupName;
        return this;
    }

    public String getKey() {
        return this.key;
    }

    public SysDictPojo setKey(String key) {
        this.key = key;
        return this;
    }

    public String getValue() {
        return this.value;
    }

    public SysDictPojo setValue(String value) {
        this.value = value;
        return this;
    }

    public String getDescription() {
        return this.description;
    }

    public SysDictPojo setDescription(String description) {
        this.description = description;
        return this;
    }

    public Integer getSort() {
        return this.sort;
    }

    public SysDictPojo setSort(Integer sort) {
        this.sort = sort;
        return this;
    }

    public SysDictStatus getStatus() {
        return this.status;
    }

    public SysDictPojo setStatus(SysDictStatus status) {
        this.status = status;
        return this;
    }

    public Timestamp getCreateAt() {
        return this.createAt;
    }

    public SysDictPojo setCreateAt(Timestamp createAt) {
        this.createAt = createAt;
        return this;
    }

    public Timestamp getUpdateAt() {
        return this.updateAt;
    }

    public SysDictPojo setUpdateAt(Timestamp updateAt) {
        this.updateAt = updateAt;
        return this;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public SysDictPojo setRemarks(String remarks) {
        this.remarks = remarks;
        return this;
    }

    public Boolean getDelFlag() {
        return this.delFlag;
    }

    public SysDictPojo setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
        return this;
    }

    public Long getVersion() {
        return this.version;
    }

    public SysDictPojo setVersion(Long version) {
        this.version = version;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysDictPojo (");

        sb.append(id);
        sb.append(", ").append(label);
        sb.append(", ").append(groupName);
        sb.append(", ").append(key);
        sb.append(", ").append(value);
        sb.append(", ").append(description);
        sb.append(", ").append(sort);
        sb.append(", ").append(status);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(remarks);
        sb.append(", ").append(delFlag);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
