/*
 * This file is generated by jOOQ.
*/
package com.dreamer.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 日志表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysLogPojo implements Serializable {

    private static final long serialVersionUID = 2129002071;

    private Long      id;
    private String    moduleName;
    private String    moduleDesc;
    private String    remoteAddr;
    private Long      operateId;
    private String    operateName;
    private String    operateMethod;
    private String    requestUrl;
    private String    params;
    private String    result;
    private String    exception;
    private Timestamp operateTime;

    public SysLogPojo() {}

    public SysLogPojo(SysLogPojo value) {
        this.id = value.id;
        this.moduleName = value.moduleName;
        this.moduleDesc = value.moduleDesc;
        this.remoteAddr = value.remoteAddr;
        this.operateId = value.operateId;
        this.operateName = value.operateName;
        this.operateMethod = value.operateMethod;
        this.requestUrl = value.requestUrl;
        this.params = value.params;
        this.result = value.result;
        this.exception = value.exception;
        this.operateTime = value.operateTime;
    }

    public SysLogPojo(
        Long      id,
        String    moduleName,
        String    moduleDesc,
        String    remoteAddr,
        Long      operateId,
        String    operateName,
        String    operateMethod,
        String    requestUrl,
        String    params,
        String    result,
        String    exception,
        Timestamp operateTime
    ) {
        this.id = id;
        this.moduleName = moduleName;
        this.moduleDesc = moduleDesc;
        this.remoteAddr = remoteAddr;
        this.operateId = operateId;
        this.operateName = operateName;
        this.operateMethod = operateMethod;
        this.requestUrl = requestUrl;
        this.params = params;
        this.result = result;
        this.exception = exception;
        this.operateTime = operateTime;
    }

    public Long getId() {
        return this.id;
    }

    public SysLogPojo setId(Long id) {
        this.id = id;
        return this;
    }

    public String getModuleName() {
        return this.moduleName;
    }

    public SysLogPojo setModuleName(String moduleName) {
        this.moduleName = moduleName;
        return this;
    }

    public String getModuleDesc() {
        return this.moduleDesc;
    }

    public SysLogPojo setModuleDesc(String moduleDesc) {
        this.moduleDesc = moduleDesc;
        return this;
    }

    public String getRemoteAddr() {
        return this.remoteAddr;
    }

    public SysLogPojo setRemoteAddr(String remoteAddr) {
        this.remoteAddr = remoteAddr;
        return this;
    }

    public Long getOperateId() {
        return this.operateId;
    }

    public SysLogPojo setOperateId(Long operateId) {
        this.operateId = operateId;
        return this;
    }

    public String getOperateName() {
        return this.operateName;
    }

    public SysLogPojo setOperateName(String operateName) {
        this.operateName = operateName;
        return this;
    }

    public String getOperateMethod() {
        return this.operateMethod;
    }

    public SysLogPojo setOperateMethod(String operateMethod) {
        this.operateMethod = operateMethod;
        return this;
    }

    public String getRequestUrl() {
        return this.requestUrl;
    }

    public SysLogPojo setRequestUrl(String requestUrl) {
        this.requestUrl = requestUrl;
        return this;
    }

    public String getParams() {
        return this.params;
    }

    public SysLogPojo setParams(String params) {
        this.params = params;
        return this;
    }

    public String getResult() {
        return this.result;
    }

    public SysLogPojo setResult(String result) {
        this.result = result;
        return this;
    }

    public String getException() {
        return this.exception;
    }

    public SysLogPojo setException(String exception) {
        this.exception = exception;
        return this;
    }

    public Timestamp getOperateTime() {
        return this.operateTime;
    }

    public SysLogPojo setOperateTime(Timestamp operateTime) {
        this.operateTime = operateTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysLogPojo (");

        sb.append(id);
        sb.append(", ").append(moduleName);
        sb.append(", ").append(moduleDesc);
        sb.append(", ").append(remoteAddr);
        sb.append(", ").append(operateId);
        sb.append(", ").append(operateName);
        sb.append(", ").append(operateMethod);
        sb.append(", ").append(requestUrl);
        sb.append(", ").append(params);
        sb.append(", ").append(result);
        sb.append(", ").append(exception);
        sb.append(", ").append(operateTime);

        sb.append(")");
        return sb.toString();
    }
}
