/*
 * This file is generated by jOOQ.
*/
package com.dreamer.domain.tables.pojos;


import com.dreamer.domain.enums.SysMenuStatus;
import com.dreamer.domain.enums.SysMenuType;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 菜单表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysMenuPojo implements Serializable {

    private static final long serialVersionUID = -466337487;

    private Long          id;
    private Long          parentId;
    private SysMenuType   type;
    private String        name;
    private String        href;
    private String        target;
    private String        icon;
    private Integer       sort;
    private SysMenuStatus status;
    private String        permission;
    private Timestamp     createAt;
    private Timestamp     updateAt;
    private String        remarks;
    private Boolean       delFlag;
    private Long          version;

    public SysMenuPojo() {}

    public SysMenuPojo(SysMenuPojo value) {
        this.id = value.id;
        this.parentId = value.parentId;
        this.type = value.type;
        this.name = value.name;
        this.href = value.href;
        this.target = value.target;
        this.icon = value.icon;
        this.sort = value.sort;
        this.status = value.status;
        this.permission = value.permission;
        this.createAt = value.createAt;
        this.updateAt = value.updateAt;
        this.remarks = value.remarks;
        this.delFlag = value.delFlag;
        this.version = value.version;
    }

    public SysMenuPojo(
        Long          id,
        Long          parentId,
        SysMenuType   type,
        String        name,
        String        href,
        String        target,
        String        icon,
        Integer       sort,
        SysMenuStatus status,
        String        permission,
        Timestamp     createAt,
        Timestamp     updateAt,
        String        remarks,
        Boolean       delFlag,
        Long          version
    ) {
        this.id = id;
        this.parentId = parentId;
        this.type = type;
        this.name = name;
        this.href = href;
        this.target = target;
        this.icon = icon;
        this.sort = sort;
        this.status = status;
        this.permission = permission;
        this.createAt = createAt;
        this.updateAt = updateAt;
        this.remarks = remarks;
        this.delFlag = delFlag;
        this.version = version;
    }

    public Long getId() {
        return this.id;
    }

    public SysMenuPojo setId(Long id) {
        this.id = id;
        return this;
    }

    public Long getParentId() {
        return this.parentId;
    }

    public SysMenuPojo setParentId(Long parentId) {
        this.parentId = parentId;
        return this;
    }

    public SysMenuType getType() {
        return this.type;
    }

    public SysMenuPojo setType(SysMenuType type) {
        this.type = type;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public SysMenuPojo setName(String name) {
        this.name = name;
        return this;
    }

    public String getHref() {
        return this.href;
    }

    public SysMenuPojo setHref(String href) {
        this.href = href;
        return this;
    }

    public String getTarget() {
        return this.target;
    }

    public SysMenuPojo setTarget(String target) {
        this.target = target;
        return this;
    }

    public String getIcon() {
        return this.icon;
    }

    public SysMenuPojo setIcon(String icon) {
        this.icon = icon;
        return this;
    }

    public Integer getSort() {
        return this.sort;
    }

    public SysMenuPojo setSort(Integer sort) {
        this.sort = sort;
        return this;
    }

    public SysMenuStatus getStatus() {
        return this.status;
    }

    public SysMenuPojo setStatus(SysMenuStatus status) {
        this.status = status;
        return this;
    }

    public String getPermission() {
        return this.permission;
    }

    public SysMenuPojo setPermission(String permission) {
        this.permission = permission;
        return this;
    }

    public Timestamp getCreateAt() {
        return this.createAt;
    }

    public SysMenuPojo setCreateAt(Timestamp createAt) {
        this.createAt = createAt;
        return this;
    }

    public Timestamp getUpdateAt() {
        return this.updateAt;
    }

    public SysMenuPojo setUpdateAt(Timestamp updateAt) {
        this.updateAt = updateAt;
        return this;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public SysMenuPojo setRemarks(String remarks) {
        this.remarks = remarks;
        return this;
    }

    public Boolean getDelFlag() {
        return this.delFlag;
    }

    public SysMenuPojo setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
        return this;
    }

    public Long getVersion() {
        return this.version;
    }

    public SysMenuPojo setVersion(Long version) {
        this.version = version;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysMenuPojo (");

        sb.append(id);
        sb.append(", ").append(parentId);
        sb.append(", ").append(type);
        sb.append(", ").append(name);
        sb.append(", ").append(href);
        sb.append(", ").append(target);
        sb.append(", ").append(icon);
        sb.append(", ").append(sort);
        sb.append(", ").append(status);
        sb.append(", ").append(permission);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(remarks);
        sb.append(", ").append(delFlag);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
