/*
 * This file is generated by jOOQ.
*/
package com.dreamer.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 角色表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRolePojo implements Serializable {

    private static final long serialVersionUID = -1100170357;

    private Long      id;
    private String    name;
    private String    createBy;
    private Timestamp createAt;
    private String    updateBy;
    private Timestamp updateAt;
    private String    remarks;
    private Boolean   delFlag;

    public SysRolePojo() {}

    public SysRolePojo(SysRolePojo value) {
        this.id = value.id;
        this.name = value.name;
        this.createBy = value.createBy;
        this.createAt = value.createAt;
        this.updateBy = value.updateBy;
        this.updateAt = value.updateAt;
        this.remarks = value.remarks;
        this.delFlag = value.delFlag;
    }

    public SysRolePojo(
        Long      id,
        String    name,
        String    createBy,
        Timestamp createAt,
        String    updateBy,
        Timestamp updateAt,
        String    remarks,
        Boolean   delFlag
    ) {
        this.id = id;
        this.name = name;
        this.createBy = createBy;
        this.createAt = createAt;
        this.updateBy = updateBy;
        this.updateAt = updateAt;
        this.remarks = remarks;
        this.delFlag = delFlag;
    }

    public Long getId() {
        return this.id;
    }

    public SysRolePojo setId(Long id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public SysRolePojo setName(String name) {
        this.name = name;
        return this;
    }

    public String getCreateBy() {
        return this.createBy;
    }

    public SysRolePojo setCreateBy(String createBy) {
        this.createBy = createBy;
        return this;
    }

    public Timestamp getCreateAt() {
        return this.createAt;
    }

    public SysRolePojo setCreateAt(Timestamp createAt) {
        this.createAt = createAt;
        return this;
    }

    public String getUpdateBy() {
        return this.updateBy;
    }

    public SysRolePojo setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
        return this;
    }

    public Timestamp getUpdateAt() {
        return this.updateAt;
    }

    public SysRolePojo setUpdateAt(Timestamp updateAt) {
        this.updateAt = updateAt;
        return this;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public SysRolePojo setRemarks(String remarks) {
        this.remarks = remarks;
        return this;
    }

    public Boolean getDelFlag() {
        return this.delFlag;
    }

    public SysRolePojo setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysRolePojo (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(createBy);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateBy);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(remarks);
        sb.append(", ").append(delFlag);

        sb.append(")");
        return sb.toString();
    }
}
