/*
 * This file is generated by jOOQ.
*/
package com.dreamer.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 角色-菜单
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRoleMenuPojo implements Serializable {

    private static final long serialVersionUID = 1753572126;

    private Long id;
    private Long sysRoleId;
    private Long sysMenuId;

    public SysRoleMenuPojo() {}

    public SysRoleMenuPojo(SysRoleMenuPojo value) {
        this.id = value.id;
        this.sysRoleId = value.sysRoleId;
        this.sysMenuId = value.sysMenuId;
    }

    public SysRoleMenuPojo(
        Long id,
        Long sysRoleId,
        Long sysMenuId
    ) {
        this.id = id;
        this.sysRoleId = sysRoleId;
        this.sysMenuId = sysMenuId;
    }

    public Long getId() {
        return this.id;
    }

    public SysRoleMenuPojo setId(Long id) {
        this.id = id;
        return this;
    }

    public Long getSysRoleId() {
        return this.sysRoleId;
    }

    public SysRoleMenuPojo setSysRoleId(Long sysRoleId) {
        this.sysRoleId = sysRoleId;
        return this;
    }

    public Long getSysMenuId() {
        return this.sysMenuId;
    }

    public SysRoleMenuPojo setSysMenuId(Long sysMenuId) {
        this.sysMenuId = sysMenuId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysRoleMenuPojo (");

        sb.append(id);
        sb.append(", ").append(sysRoleId);
        sb.append(", ").append(sysMenuId);

        sb.append(")");
        return sb.toString();
    }
}
