/*
 * This file is generated by jOOQ.
*/
package com.dreamer.domain.tables.pojos;


import com.dreamer.domain.enums.SysUserStatus;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 用户表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserPojo implements Serializable {

    private static final long serialVersionUID = -487729196;

    private Long          id;
    private String        loginName;
    private String        password;
    private String        no;
    private String        name;
    private String        email;
    private String        phone;
    private String        mobile;
    private SysUserStatus status;
    private String        loginIp;
    private Timestamp     loginTime;
    private String        avatars;
    private Timestamp     createAt;
    private Timestamp     updateAt;
    private String        remarks;
    private Boolean       delFlag;

    public SysUserPojo() {}

    public SysUserPojo(SysUserPojo value) {
        this.id = value.id;
        this.loginName = value.loginName;
        this.password = value.password;
        this.no = value.no;
        this.name = value.name;
        this.email = value.email;
        this.phone = value.phone;
        this.mobile = value.mobile;
        this.status = value.status;
        this.loginIp = value.loginIp;
        this.loginTime = value.loginTime;
        this.avatars = value.avatars;
        this.createAt = value.createAt;
        this.updateAt = value.updateAt;
        this.remarks = value.remarks;
        this.delFlag = value.delFlag;
    }

    public SysUserPojo(
        Long          id,
        String        loginName,
        String        password,
        String        no,
        String        name,
        String        email,
        String        phone,
        String        mobile,
        SysUserStatus status,
        String        loginIp,
        Timestamp     loginTime,
        String        avatars,
        Timestamp     createAt,
        Timestamp     updateAt,
        String        remarks,
        Boolean       delFlag
    ) {
        this.id = id;
        this.loginName = loginName;
        this.password = password;
        this.no = no;
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.mobile = mobile;
        this.status = status;
        this.loginIp = loginIp;
        this.loginTime = loginTime;
        this.avatars = avatars;
        this.createAt = createAt;
        this.updateAt = updateAt;
        this.remarks = remarks;
        this.delFlag = delFlag;
    }

    public Long getId() {
        return this.id;
    }

    public SysUserPojo setId(Long id) {
        this.id = id;
        return this;
    }

    public String getLoginName() {
        return this.loginName;
    }

    public SysUserPojo setLoginName(String loginName) {
        this.loginName = loginName;
        return this;
    }

    public String getPassword() {
        return this.password;
    }

    public SysUserPojo setPassword(String password) {
        this.password = password;
        return this;
    }

    public String getNo() {
        return this.no;
    }

    public SysUserPojo setNo(String no) {
        this.no = no;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public SysUserPojo setName(String name) {
        this.name = name;
        return this;
    }

    public String getEmail() {
        return this.email;
    }

    public SysUserPojo setEmail(String email) {
        this.email = email;
        return this;
    }

    public String getPhone() {
        return this.phone;
    }

    public SysUserPojo setPhone(String phone) {
        this.phone = phone;
        return this;
    }

    public String getMobile() {
        return this.mobile;
    }

    public SysUserPojo setMobile(String mobile) {
        this.mobile = mobile;
        return this;
    }

    public SysUserStatus getStatus() {
        return this.status;
    }

    public SysUserPojo setStatus(SysUserStatus status) {
        this.status = status;
        return this;
    }

    public String getLoginIp() {
        return this.loginIp;
    }

    public SysUserPojo setLoginIp(String loginIp) {
        this.loginIp = loginIp;
        return this;
    }

    public Timestamp getLoginTime() {
        return this.loginTime;
    }

    public SysUserPojo setLoginTime(Timestamp loginTime) {
        this.loginTime = loginTime;
        return this;
    }

    public String getAvatars() {
        return this.avatars;
    }

    public SysUserPojo setAvatars(String avatars) {
        this.avatars = avatars;
        return this;
    }

    public Timestamp getCreateAt() {
        return this.createAt;
    }

    public SysUserPojo setCreateAt(Timestamp createAt) {
        this.createAt = createAt;
        return this;
    }

    public Timestamp getUpdateAt() {
        return this.updateAt;
    }

    public SysUserPojo setUpdateAt(Timestamp updateAt) {
        this.updateAt = updateAt;
        return this;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public SysUserPojo setRemarks(String remarks) {
        this.remarks = remarks;
        return this;
    }

    public Boolean getDelFlag() {
        return this.delFlag;
    }

    public SysUserPojo setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysUserPojo (");

        sb.append(id);
        sb.append(", ").append(loginName);
        sb.append(", ").append(password);
        sb.append(", ").append(no);
        sb.append(", ").append(name);
        sb.append(", ").append(email);
        sb.append(", ").append(phone);
        sb.append(", ").append(mobile);
        sb.append(", ").append(status);
        sb.append(", ").append(loginIp);
        sb.append(", ").append(loginTime);
        sb.append(", ").append(avatars);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(remarks);
        sb.append(", ").append(delFlag);

        sb.append(")");
        return sb.toString();
    }
}
