/*
 * This file is generated by jOOQ.
*/
package com.dreamer.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 用户-角色
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserRolePojo implements Serializable {

    private static final long serialVersionUID = -687766676;

    private Long id;
    private Long sysUserId;
    private Long sysRoleId;

    public SysUserRolePojo() {}

    public SysUserRolePojo(SysUserRolePojo value) {
        this.id = value.id;
        this.sysUserId = value.sysUserId;
        this.sysRoleId = value.sysRoleId;
    }

    public SysUserRolePojo(
        Long id,
        Long sysUserId,
        Long sysRoleId
    ) {
        this.id = id;
        this.sysUserId = sysUserId;
        this.sysRoleId = sysRoleId;
    }

    public Long getId() {
        return this.id;
    }

    public SysUserRolePojo setId(Long id) {
        this.id = id;
        return this;
    }

    public Long getSysUserId() {
        return this.sysUserId;
    }

    public SysUserRolePojo setSysUserId(Long sysUserId) {
        this.sysUserId = sysUserId;
        return this;
    }

    public Long getSysRoleId() {
        return this.sysRoleId;
    }

    public SysUserRolePojo setSysRoleId(Long sysRoleId) {
        this.sysRoleId = sysRoleId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysUserRolePojo (");

        sb.append(id);
        sb.append(", ").append(sysUserId);
        sb.append(", ").append(sysRoleId);

        sb.append(")");
        return sb.toString();
    }
}
