/*
 * This file is generated by jOOQ.
*/
package com.dreamer.admin.domain.tables.records;


import com.dreamer.admin.domain.enums.BscFileBizType;
import com.dreamer.admin.domain.enums.BscFileFileStatus;
import com.dreamer.admin.domain.tables.BscFile;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * 文件表
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class BscFileRecord extends UpdatableRecordImpl<BscFileRecord> implements Record12<Long, String, String, BscFileBizType, Long, Integer, BscFileFileStatus, Timestamp, Timestamp, String, Boolean, Long> {

    private static final long serialVersionUID = -1864757098;

    /**
     * Create a detached BscFileRecord
     */
    public BscFileRecord() {
        super(BscFile.BSC_FILE);
    }

    /**
     * Create a detached, initialised BscFileRecord
     */
    public BscFileRecord(Long id, String fileName, String fileUrl, BscFileBizType bizType, Long sourceId, Integer order, BscFileFileStatus fileStatus, Timestamp createAt, Timestamp updateAt, String remark, Boolean delFlag, Long version) {
        super(BscFile.BSC_FILE);

        set(0, id);
        set(1, fileName);
        set(2, fileUrl);
        set(3, bizType);
        set(4, sourceId);
        set(5, order);
        set(6, fileStatus);
        set(7, createAt);
        set(8, updateAt);
        set(9, remark);
        set(10, delFlag);
        set(11, version);
    }

    /**
     * Getter for <code>dreamer.bsc_file.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>dreamer.bsc_file.id</code>. 主键
     */
    public BscFileRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>dreamer.bsc_file.file_name</code>. 文件名字
     */
    public String getFileName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>dreamer.bsc_file.file_name</code>. 文件名字
     */
    public BscFileRecord setFileName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>dreamer.bsc_file.file_url</code>. 文件url
     */
    public String getFileUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>dreamer.bsc_file.file_url</code>. 文件url
     */
    public BscFileRecord setFileUrl(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>dreamer.bsc_file.biz_type</code>. 业务类型：机构banner；课程banner；
     */
    public BscFileBizType getBizType() {
        return (BscFileBizType) get(3);
    }

    /**
     * Setter for <code>dreamer.bsc_file.biz_type</code>. 业务类型：机构banner；课程banner；
     */
    public BscFileRecord setBizType(BscFileBizType value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>dreamer.bsc_file.source_id</code>. 业务ID
     */
    public Long getSourceId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>dreamer.bsc_file.source_id</code>. 业务ID
     */
    public BscFileRecord setSourceId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>dreamer.bsc_file.order</code>.
     */
    public Integer getOrder() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>dreamer.bsc_file.order</code>.
     */
    public BscFileRecord setOrder(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>dreamer.bsc_file.file_status</code>. 文件状态：可用；不可用
     */
    public BscFileFileStatus getFileStatus() {
        return (BscFileFileStatus) get(6);
    }

    /**
     * Setter for <code>dreamer.bsc_file.file_status</code>. 文件状态：可用；不可用
     */
    public BscFileRecord setFileStatus(BscFileFileStatus value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>dreamer.bsc_file.create_at</code>. 创建时间
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>dreamer.bsc_file.create_at</code>. 创建时间
     */
    public BscFileRecord setCreateAt(Timestamp value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>dreamer.bsc_file.update_at</code>. 更新时间
     */
    public Timestamp getUpdateAt() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>dreamer.bsc_file.update_at</code>. 更新时间
     */
    public BscFileRecord setUpdateAt(Timestamp value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>dreamer.bsc_file.remark</code>. 备注信息
     */
    public String getRemark() {
        return (String) get(9);
    }

    /**
     * Setter for <code>dreamer.bsc_file.remark</code>. 备注信息
     */
    public BscFileRecord setRemark(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>dreamer.bsc_file.del_flag</code>. 删除标志
     */
    public Boolean getDelFlag() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>dreamer.bsc_file.del_flag</code>. 删除标志
     */
    public BscFileRecord setDelFlag(Boolean value) {
        set(10, value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>dreamer.bsc_file.version</code>.
     */
    public Long getVersion() {
        return (Long) get(11);
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>dreamer.bsc_file.version</code>.
     */
    public BscFileRecord setVersion(Long value) {
        set(11, value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, String, String, BscFileBizType, Long, Integer, BscFileFileStatus, Timestamp, Timestamp, String, Boolean, Long> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, String, String, BscFileBizType, Long, Integer, BscFileFileStatus, Timestamp, Timestamp, String, Boolean, Long> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return BscFile.BSC_FILE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BscFile.BSC_FILE.FILE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return BscFile.BSC_FILE.FILE_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BscFileBizType> field4() {
        return BscFile.BSC_FILE.BIZ_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return BscFile.BSC_FILE.SOURCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return BscFile.BSC_FILE.ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BscFileFileStatus> field7() {
        return BscFile.BSC_FILE.FILE_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return BscFile.BSC_FILE.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return BscFile.BSC_FILE.UPDATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return BscFile.BSC_FILE.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field11() {
        return BscFile.BSC_FILE.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return BscFile.BSC_FILE.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFileName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFileUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BscFileBizType value4() {
        return getBizType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getSourceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BscFileFileStatus value7() {
        return getFileStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value11() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BscFileRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BscFileRecord value2(String value) {
        setFileName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BscFileRecord value3(String value) {
        setFileUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BscFileRecord value4(BscFileBizType value) {
        setBizType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BscFileRecord value5(Long value) {
        setSourceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BscFileRecord value6(Integer value) {
        setOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BscFileRecord value7(BscFileFileStatus value) {
        setFileStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BscFileRecord value8(Timestamp value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BscFileRecord value9(Timestamp value) {
        setUpdateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BscFileRecord value10(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BscFileRecord value11(Boolean value) {
        setDelFlag(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public BscFileRecord value12(Long value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BscFileRecord values(Long value1, String value2, String value3, BscFileBizType value4, Long value5, Integer value6, BscFileFileStatus value7, Timestamp value8, Timestamp value9, String value10, Boolean value11, Long value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }
}
