/*
 * This file is generated by jOOQ.
*/
package com.dreamer.admin.domain.tables.records;


import com.dreamer.admin.domain.tables.OgnInfo;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * 机构信息表
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class OgnInfoRecord extends UpdatableRecordImpl<OgnInfoRecord> implements Record9<Long, String, String, String, String, Timestamp, String, String, String> {

    private static final long serialVersionUID = -1012626200;

    /**
     * Create a detached OgnInfoRecord
     */
    public OgnInfoRecord() {
        super(OgnInfo.OGN_INFO);
    }

    /**
     * Create a detached, initialised OgnInfoRecord
     */
    public OgnInfoRecord(Long id, String organName, String organEnglishName, String organAddress, String organShortIntroduce, Timestamp organCreateDate, String organPhone, String organEmail, String orgenUrl) {
        super(OgnInfo.OGN_INFO);

        set(0, id);
        set(1, organName);
        set(2, organEnglishName);
        set(3, organAddress);
        set(4, organShortIntroduce);
        set(5, organCreateDate);
        set(6, organPhone);
        set(7, organEmail);
        set(8, orgenUrl);
    }

    /**
     * Getter for <code>dreamer.ogn_info.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>dreamer.ogn_info.id</code>. 主键
     */
    public OgnInfoRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>dreamer.ogn_info.organ_name</code>. 机构名称
     */
    public String getOrganName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>dreamer.ogn_info.organ_name</code>. 机构名称
     */
    public OgnInfoRecord setOrganName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>dreamer.ogn_info.organ_english_name</code>. 机构英文名称
     */
    public String getOrganEnglishName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>dreamer.ogn_info.organ_english_name</code>. 机构英文名称
     */
    public OgnInfoRecord setOrganEnglishName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>dreamer.ogn_info.organ_address</code>. 机构地址
     */
    public String getOrganAddress() {
        return (String) get(3);
    }

    /**
     * Setter for <code>dreamer.ogn_info.organ_address</code>. 机构地址
     */
    public OgnInfoRecord setOrganAddress(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>dreamer.ogn_info.organ_short_introduce</code>. 机构简介
     */
    public String getOrganShortIntroduce() {
        return (String) get(4);
    }

    /**
     * Setter for <code>dreamer.ogn_info.organ_short_introduce</code>. 机构简介
     */
    public OgnInfoRecord setOrganShortIntroduce(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>dreamer.ogn_info.organ_create_date</code>. 机构成立日期
     */
    public Timestamp getOrganCreateDate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>dreamer.ogn_info.organ_create_date</code>. 机构成立日期
     */
    public OgnInfoRecord setOrganCreateDate(Timestamp value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>dreamer.ogn_info.organ_phone</code>. 机构官方电话
     */
    public String getOrganPhone() {
        return (String) get(6);
    }

    /**
     * Setter for <code>dreamer.ogn_info.organ_phone</code>. 机构官方电话
     */
    public OgnInfoRecord setOrganPhone(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>dreamer.ogn_info.organ_email</code>. 机构官方邮箱
     */
    public String getOrganEmail() {
        return (String) get(7);
    }

    /**
     * Setter for <code>dreamer.ogn_info.organ_email</code>. 机构官方邮箱
     */
    public OgnInfoRecord setOrganEmail(String value) {
        set(7, value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>dreamer.ogn_info.orgen_url</code>. 机构官方网址
     */
    public String getOrgenUrl() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>dreamer.ogn_info.orgen_url</code>. 机构官方网址
     */
    public OgnInfoRecord setOrgenUrl(String value) {
        set(8, value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, String, String, String, Timestamp, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, String, String, String, Timestamp, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return OgnInfo.OGN_INFO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return OgnInfo.OGN_INFO.ORGAN_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return OgnInfo.OGN_INFO.ORGAN_ENGLISH_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return OgnInfo.OGN_INFO.ORGAN_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return OgnInfo.OGN_INFO.ORGAN_SHORT_INTRODUCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return OgnInfo.OGN_INFO.ORGAN_CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return OgnInfo.OGN_INFO.ORGAN_PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return OgnInfo.OGN_INFO.ORGAN_EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return OgnInfo.OGN_INFO.ORGEN_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getOrganName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOrganEnglishName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getOrganAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getOrganShortIntroduce();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getOrganCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getOrganPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getOrganEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getOrgenUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OgnInfoRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OgnInfoRecord value2(String value) {
        setOrganName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OgnInfoRecord value3(String value) {
        setOrganEnglishName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OgnInfoRecord value4(String value) {
        setOrganAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OgnInfoRecord value5(String value) {
        setOrganShortIntroduce(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OgnInfoRecord value6(Timestamp value) {
        setOrganCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OgnInfoRecord value7(String value) {
        setOrganPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OgnInfoRecord value8(String value) {
        setOrganEmail(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public OgnInfoRecord value9(String value) {
        setOrgenUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OgnInfoRecord values(Long value1, String value2, String value3, String value4, String value5, Timestamp value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }
}
