/*
 * This file is generated by jOOQ.
*/
package com.dreamer.admin.domain;


import com.dreamer.admin.domain.tables.*;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Dreamer extends SchemaImpl {

    /**
     * The reference instance of <code>dreamer</code>
     */
    public static final Dreamer DREAMER = new Dreamer();
    private static final long serialVersionUID = 302443994;
    /**
     * 文件表
     */
    public final BscFile BSC_FILE = com.dreamer.admin.domain.tables.BscFile.BSC_FILE;

    /**
     * The table <code>dreamer.cst_course_catalog</code>.
     */
    public final CstCourseCatalog CST_COURSE_CATALOG = com.dreamer.admin.domain.tables.CstCourseCatalog.CST_COURSE_CATALOG;

    /**
     * 机构课程表
     */
    public final OgnCourse OGN_COURSE = com.dreamer.admin.domain.tables.OgnCourse.OGN_COURSE;

    /**
     * 机构信息表
     */
    public final OgnInfo OGN_INFO = com.dreamer.admin.domain.tables.OgnInfo.OGN_INFO;

    /**
     * 字典表
     */
    public final SysDict SYS_DICT = com.dreamer.admin.domain.tables.SysDict.SYS_DICT;

    /**
     * 日志表
     */
    public final SysLog SYS_LOG = com.dreamer.admin.domain.tables.SysLog.SYS_LOG;

    /**
     * 菜单表
     */
    public final SysMenu SYS_MENU = com.dreamer.admin.domain.tables.SysMenu.SYS_MENU;

    /**
     * 角色表
     */
    public final SysRole SYS_ROLE = com.dreamer.admin.domain.tables.SysRole.SYS_ROLE;

    /**
     * 角色-菜单
     */
    public final SysRoleMenu SYS_ROLE_MENU = com.dreamer.admin.domain.tables.SysRoleMenu.SYS_ROLE_MENU;

    /**
     * 用户表
     */
    public final SysUser SYS_USER = com.dreamer.admin.domain.tables.SysUser.SYS_USER;

    /**
     * 用户-角色
     */
    public final SysUserRole SYS_USER_ROLE = com.dreamer.admin.domain.tables.SysUserRole.SYS_USER_ROLE;

    /**
     * 微信会话token表
     */
    public final WcSessionToken WC_SESSION_TOKEN = com.dreamer.admin.domain.tables.WcSessionToken.WC_SESSION_TOKEN;

    /**
     * No further instances allowed
     */
    private Dreamer() {
        super("dreamer", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
                BscFile.BSC_FILE,
                CstCourseCatalog.CST_COURSE_CATALOG,
                OgnCourse.OGN_COURSE,
                OgnInfo.OGN_INFO,
                SysDict.SYS_DICT,
                SysLog.SYS_LOG,
                SysMenu.SYS_MENU,
                SysRole.SYS_ROLE,
                SysRoleMenu.SYS_ROLE_MENU,
                SysUser.SYS_USER,
                SysUserRole.SYS_USER_ROLE,
                WcSessionToken.WC_SESSION_TOKEN);
    }
}
