/*
 * This file is generated by jOOQ.
*/
package com.dreamer.admin.domain;


import com.dreamer.admin.domain.tables.*;
import com.dreamer.admin.domain.tables.records.*;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships between tables of the <code>dreamer</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<BscFileRecord, Long> IDENTITY_BSC_FILE = Identities0.IDENTITY_BSC_FILE;
    public static final Identity<OgnInfoRecord, Long> IDENTITY_OGN_INFO = Identities0.IDENTITY_OGN_INFO;
    public static final Identity<SysDictRecord, Long> IDENTITY_SYS_DICT = Identities0.IDENTITY_SYS_DICT;
    public static final Identity<SysLogRecord, Long> IDENTITY_SYS_LOG = Identities0.IDENTITY_SYS_LOG;
    public static final Identity<SysMenuRecord, Long> IDENTITY_SYS_MENU = Identities0.IDENTITY_SYS_MENU;
    public static final Identity<SysRoleRecord, Long> IDENTITY_SYS_ROLE = Identities0.IDENTITY_SYS_ROLE;
    public static final Identity<SysRoleMenuRecord, Long> IDENTITY_SYS_ROLE_MENU = Identities0.IDENTITY_SYS_ROLE_MENU;
    public static final Identity<SysUserRecord, Long> IDENTITY_SYS_USER = Identities0.IDENTITY_SYS_USER;
    public static final Identity<SysUserRoleRecord, Long> IDENTITY_SYS_USER_ROLE = Identities0.IDENTITY_SYS_USER_ROLE;
    public static final Identity<WcSessionTokenRecord, Long> IDENTITY_WC_SESSION_TOKEN = Identities0.IDENTITY_WC_SESSION_TOKEN;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BscFileRecord> KEY_BSC_FILE_PRIMARY = UniqueKeys0.KEY_BSC_FILE_PRIMARY;
    public static final UniqueKey<OgnCourseRecord> KEY_OGN_COURSE_PRIMARY = UniqueKeys0.KEY_OGN_COURSE_PRIMARY;
    public static final UniqueKey<OgnInfoRecord> KEY_OGN_INFO_PRIMARY = UniqueKeys0.KEY_OGN_INFO_PRIMARY;
    public static final UniqueKey<SysDictRecord> KEY_SYS_DICT_PRIMARY = UniqueKeys0.KEY_SYS_DICT_PRIMARY;
    public static final UniqueKey<SysDictRecord> KEY_SYS_DICT_SYS_DICT_GROUPNAME_KEY = UniqueKeys0.KEY_SYS_DICT_SYS_DICT_GROUPNAME_KEY;
    public static final UniqueKey<SysLogRecord> KEY_SYS_LOG_PRIMARY = UniqueKeys0.KEY_SYS_LOG_PRIMARY;
    public static final UniqueKey<SysMenuRecord> KEY_SYS_MENU_PRIMARY = UniqueKeys0.KEY_SYS_MENU_PRIMARY;
    public static final UniqueKey<SysRoleRecord> KEY_SYS_ROLE_PRIMARY = UniqueKeys0.KEY_SYS_ROLE_PRIMARY;
    public static final UniqueKey<SysRoleMenuRecord> KEY_SYS_ROLE_MENU_PRIMARY = UniqueKeys0.KEY_SYS_ROLE_MENU_PRIMARY;
    public static final UniqueKey<SysUserRecord> KEY_SYS_USER_PRIMARY = UniqueKeys0.KEY_SYS_USER_PRIMARY;
    public static final UniqueKey<SysUserRecord> KEY_SYS_USER_SYS_USER_LOGIN_NAME = UniqueKeys0.KEY_SYS_USER_SYS_USER_LOGIN_NAME;
    public static final UniqueKey<SysUserRoleRecord> KEY_SYS_USER_ROLE_PRIMARY = UniqueKeys0.KEY_SYS_USER_ROLE_PRIMARY;
    public static final UniqueKey<WcSessionTokenRecord> KEY_WC_SESSION_TOKEN_PRIMARY = UniqueKeys0.KEY_WC_SESSION_TOKEN_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<BscFileRecord, Long> IDENTITY_BSC_FILE = createIdentity(BscFile.BSC_FILE, BscFile.BSC_FILE.ID);
        public static Identity<OgnInfoRecord, Long> IDENTITY_OGN_INFO = createIdentity(OgnInfo.OGN_INFO, OgnInfo.OGN_INFO.ID);
        public static Identity<SysDictRecord, Long> IDENTITY_SYS_DICT = createIdentity(SysDict.SYS_DICT, SysDict.SYS_DICT.ID);
        public static Identity<SysLogRecord, Long> IDENTITY_SYS_LOG = createIdentity(SysLog.SYS_LOG, SysLog.SYS_LOG.ID);
        public static Identity<SysMenuRecord, Long> IDENTITY_SYS_MENU = createIdentity(SysMenu.SYS_MENU, SysMenu.SYS_MENU.ID);
        public static Identity<SysRoleRecord, Long> IDENTITY_SYS_ROLE = createIdentity(SysRole.SYS_ROLE, SysRole.SYS_ROLE.ID);
        public static Identity<SysRoleMenuRecord, Long> IDENTITY_SYS_ROLE_MENU = createIdentity(SysRoleMenu.SYS_ROLE_MENU, SysRoleMenu.SYS_ROLE_MENU.ID);
        public static Identity<SysUserRecord, Long> IDENTITY_SYS_USER = createIdentity(SysUser.SYS_USER, SysUser.SYS_USER.ID);
        public static Identity<SysUserRoleRecord, Long> IDENTITY_SYS_USER_ROLE = createIdentity(SysUserRole.SYS_USER_ROLE, SysUserRole.SYS_USER_ROLE.ID);
        public static Identity<WcSessionTokenRecord, Long> IDENTITY_WC_SESSION_TOKEN = createIdentity(WcSessionToken.WC_SESSION_TOKEN, WcSessionToken.WC_SESSION_TOKEN.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<BscFileRecord> KEY_BSC_FILE_PRIMARY = createUniqueKey(BscFile.BSC_FILE, "KEY_bsc_file_PRIMARY", BscFile.BSC_FILE.ID);
        public static final UniqueKey<OgnCourseRecord> KEY_OGN_COURSE_PRIMARY = createUniqueKey(OgnCourse.OGN_COURSE, "KEY_ogn_course_PRIMARY", OgnCourse.OGN_COURSE.ID);
        public static final UniqueKey<OgnInfoRecord> KEY_OGN_INFO_PRIMARY = createUniqueKey(OgnInfo.OGN_INFO, "KEY_ogn_info_PRIMARY", OgnInfo.OGN_INFO.ID);
        public static final UniqueKey<SysDictRecord> KEY_SYS_DICT_PRIMARY = createUniqueKey(SysDict.SYS_DICT, "KEY_sys_dict_PRIMARY", SysDict.SYS_DICT.ID);
        public static final UniqueKey<SysDictRecord> KEY_SYS_DICT_SYS_DICT_GROUPNAME_KEY = createUniqueKey(SysDict.SYS_DICT, "KEY_sys_dict_sys_dict_groupname_key", SysDict.SYS_DICT.GROUP_NAME, SysDict.SYS_DICT.KEY);
        public static final UniqueKey<SysLogRecord> KEY_SYS_LOG_PRIMARY = createUniqueKey(SysLog.SYS_LOG, "KEY_sys_log_PRIMARY", SysLog.SYS_LOG.ID);
        public static final UniqueKey<SysMenuRecord> KEY_SYS_MENU_PRIMARY = createUniqueKey(SysMenu.SYS_MENU, "KEY_sys_menu_PRIMARY", SysMenu.SYS_MENU.ID);
        public static final UniqueKey<SysRoleRecord> KEY_SYS_ROLE_PRIMARY = createUniqueKey(SysRole.SYS_ROLE, "KEY_sys_role_PRIMARY", SysRole.SYS_ROLE.ID);
        public static final UniqueKey<SysRoleMenuRecord> KEY_SYS_ROLE_MENU_PRIMARY = createUniqueKey(SysRoleMenu.SYS_ROLE_MENU, "KEY_sys_role_menu_PRIMARY", SysRoleMenu.SYS_ROLE_MENU.ID, SysRoleMenu.SYS_ROLE_MENU.SYS_ROLE_ID, SysRoleMenu.SYS_ROLE_MENU.SYS_MENU_ID);
        public static final UniqueKey<SysUserRecord> KEY_SYS_USER_PRIMARY = createUniqueKey(SysUser.SYS_USER, "KEY_sys_user_PRIMARY", SysUser.SYS_USER.ID);
        public static final UniqueKey<SysUserRecord> KEY_SYS_USER_SYS_USER_LOGIN_NAME = createUniqueKey(SysUser.SYS_USER, "KEY_sys_user_sys_user_login_name", SysUser.SYS_USER.LOGIN_NAME);
        public static final UniqueKey<SysUserRoleRecord> KEY_SYS_USER_ROLE_PRIMARY = createUniqueKey(SysUserRole.SYS_USER_ROLE, "KEY_sys_user_role_PRIMARY", SysUserRole.SYS_USER_ROLE.ID, SysUserRole.SYS_USER_ROLE.SYS_USER_ID, SysUserRole.SYS_USER_ROLE.SYS_ROLE_ID);
        public static final UniqueKey<WcSessionTokenRecord> KEY_WC_SESSION_TOKEN_PRIMARY = createUniqueKey(WcSessionToken.WC_SESSION_TOKEN, "KEY_wc_session_token_PRIMARY", WcSessionToken.WC_SESSION_TOKEN.ID);
    }
}
