/*
 * This file is generated by jOOQ.
*/
package com.dreamer.domain.tables.daos;


import com.dreamer.domain.enums.SysDictStatus;
import com.dreamer.domain.tables.SysDict;
import com.dreamer.domain.tables.pojos.SysDictPojo;
import com.dreamer.domain.tables.records.SysDictRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 字典表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysDictDao extends DAOImpl<SysDictRecord, SysDictPojo, Long> {

    /**
     * Create a new SysDictDao without any configuration
     */
    public SysDictDao() {
        super(SysDict.SYS_DICT, SysDictPojo.class);
    }

    /**
     * Create a new SysDictDao with an attached configuration
     */
    public SysDictDao(Configuration configuration) {
        super(SysDict.SYS_DICT, SysDictPojo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(SysDictPojo object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<SysDictPojo> fetchById(Long... values) {
        return fetch(SysDict.SYS_DICT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public SysDictPojo fetchOneById(Long value) {
        return fetchOne(SysDict.SYS_DICT.ID, value);
    }

    /**
     * Fetch records that have <code>label IN (values)</code>
     */
    public List<SysDictPojo> fetchByLabel(String... values) {
        return fetch(SysDict.SYS_DICT.LABEL, values);
    }

    /**
     * Fetch records that have <code>group_name IN (values)</code>
     */
    public List<SysDictPojo> fetchByGroupName(String... values) {
        return fetch(SysDict.SYS_DICT.GROUP_NAME, values);
    }

    /**
     * Fetch records that have <code>key IN (values)</code>
     */
    public List<SysDictPojo> fetchByKey(String... values) {
        return fetch(SysDict.SYS_DICT.KEY, values);
    }

    /**
     * Fetch records that have <code>value IN (values)</code>
     */
    public List<SysDictPojo> fetchByValue(String... values) {
        return fetch(SysDict.SYS_DICT.VALUE, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<SysDictPojo> fetchByDescription(String... values) {
        return fetch(SysDict.SYS_DICT.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>sort IN (values)</code>
     */
    public List<SysDictPojo> fetchBySort(Integer... values) {
        return fetch(SysDict.SYS_DICT.SORT, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<SysDictPojo> fetchByStatus(SysDictStatus... values) {
        return fetch(SysDict.SYS_DICT.STATUS, values);
    }

    /**
     * Fetch records that have <code>create_at IN (values)</code>
     */
    public List<SysDictPojo> fetchByCreateAt(Timestamp... values) {
        return fetch(SysDict.SYS_DICT.CREATE_AT, values);
    }

    /**
     * Fetch records that have <code>update_at IN (values)</code>
     */
    public List<SysDictPojo> fetchByUpdateAt(Timestamp... values) {
        return fetch(SysDict.SYS_DICT.UPDATE_AT, values);
    }

    /**
     * Fetch records that have <code>remarks IN (values)</code>
     */
    public List<SysDictPojo> fetchByRemarks(String... values) {
        return fetch(SysDict.SYS_DICT.REMARKS, values);
    }

    /**
     * Fetch records that have <code>del_flag IN (values)</code>
     */
    public List<SysDictPojo> fetchByDelFlag(Boolean... values) {
        return fetch(SysDict.SYS_DICT.DEL_FLAG, values);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<SysDictPojo> fetchByVersion(Long... values) {
        return fetch(SysDict.SYS_DICT.VERSION, values);
    }
}
