/*
 * This file is generated by jOOQ.
*/
package com.dreamer.domain.tables.daos;


import com.dreamer.domain.tables.SysLog;
import com.dreamer.domain.tables.pojos.SysLogPojo;
import com.dreamer.domain.tables.records.SysLogRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 日志表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysLogDao extends DAOImpl<SysLogRecord, SysLogPojo, Long> {

    /**
     * Create a new SysLogDao without any configuration
     */
    public SysLogDao() {
        super(SysLog.SYS_LOG, SysLogPojo.class);
    }

    /**
     * Create a new SysLogDao with an attached configuration
     */
    public SysLogDao(Configuration configuration) {
        super(SysLog.SYS_LOG, SysLogPojo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(SysLogPojo object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<SysLogPojo> fetchById(Long... values) {
        return fetch(SysLog.SYS_LOG.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public SysLogPojo fetchOneById(Long value) {
        return fetchOne(SysLog.SYS_LOG.ID, value);
    }

    /**
     * Fetch records that have <code>module_name IN (values)</code>
     */
    public List<SysLogPojo> fetchByModuleName(String... values) {
        return fetch(SysLog.SYS_LOG.MODULE_NAME, values);
    }

    /**
     * Fetch records that have <code>module_desc IN (values)</code>
     */
    public List<SysLogPojo> fetchByModuleDesc(String... values) {
        return fetch(SysLog.SYS_LOG.MODULE_DESC, values);
    }

    /**
     * Fetch records that have <code>remote_addr IN (values)</code>
     */
    public List<SysLogPojo> fetchByRemoteAddr(String... values) {
        return fetch(SysLog.SYS_LOG.REMOTE_ADDR, values);
    }

    /**
     * Fetch records that have <code>operate_id IN (values)</code>
     */
    public List<SysLogPojo> fetchByOperateId(Long... values) {
        return fetch(SysLog.SYS_LOG.OPERATE_ID, values);
    }

    /**
     * Fetch records that have <code>operate_name IN (values)</code>
     */
    public List<SysLogPojo> fetchByOperateName(String... values) {
        return fetch(SysLog.SYS_LOG.OPERATE_NAME, values);
    }

    /**
     * Fetch records that have <code>operate_method IN (values)</code>
     */
    public List<SysLogPojo> fetchByOperateMethod(String... values) {
        return fetch(SysLog.SYS_LOG.OPERATE_METHOD, values);
    }

    /**
     * Fetch records that have <code>request_url IN (values)</code>
     */
    public List<SysLogPojo> fetchByRequestUrl(String... values) {
        return fetch(SysLog.SYS_LOG.REQUEST_URL, values);
    }

    /**
     * Fetch records that have <code>params IN (values)</code>
     */
    public List<SysLogPojo> fetchByParams(String... values) {
        return fetch(SysLog.SYS_LOG.PARAMS, values);
    }

    /**
     * Fetch records that have <code>result IN (values)</code>
     */
    public List<SysLogPojo> fetchByResult(String... values) {
        return fetch(SysLog.SYS_LOG.RESULT, values);
    }

    /**
     * Fetch records that have <code>exception IN (values)</code>
     */
    public List<SysLogPojo> fetchByException(String... values) {
        return fetch(SysLog.SYS_LOG.EXCEPTION, values);
    }

    /**
     * Fetch records that have <code>operate_time IN (values)</code>
     */
    public List<SysLogPojo> fetchByOperateTime(Timestamp... values) {
        return fetch(SysLog.SYS_LOG.OPERATE_TIME, values);
    }
}
