/*
 * This file is generated by jOOQ.
*/
package com.dreamer.domain.tables.daos;


import com.dreamer.domain.enums.SysMenuStatus;
import com.dreamer.domain.enums.SysMenuType;
import com.dreamer.domain.tables.SysMenu;
import com.dreamer.domain.tables.pojos.SysMenuPojo;
import com.dreamer.domain.tables.records.SysMenuRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 菜单表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysMenuDao extends DAOImpl<SysMenuRecord, SysMenuPojo, Long> {

    /**
     * Create a new SysMenuDao without any configuration
     */
    public SysMenuDao() {
        super(SysMenu.SYS_MENU, SysMenuPojo.class);
    }

    /**
     * Create a new SysMenuDao with an attached configuration
     */
    public SysMenuDao(Configuration configuration) {
        super(SysMenu.SYS_MENU, SysMenuPojo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(SysMenuPojo object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<SysMenuPojo> fetchById(Long... values) {
        return fetch(SysMenu.SYS_MENU.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public SysMenuPojo fetchOneById(Long value) {
        return fetchOne(SysMenu.SYS_MENU.ID, value);
    }

    /**
     * Fetch records that have <code>parent_id IN (values)</code>
     */
    public List<SysMenuPojo> fetchByParentId(Long... values) {
        return fetch(SysMenu.SYS_MENU.PARENT_ID, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<SysMenuPojo> fetchByType(SysMenuType... values) {
        return fetch(SysMenu.SYS_MENU.TYPE, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<SysMenuPojo> fetchByName(String... values) {
        return fetch(SysMenu.SYS_MENU.NAME, values);
    }

    /**
     * Fetch records that have <code>href IN (values)</code>
     */
    public List<SysMenuPojo> fetchByHref(String... values) {
        return fetch(SysMenu.SYS_MENU.HREF, values);
    }

    /**
     * Fetch records that have <code>target IN (values)</code>
     */
    public List<SysMenuPojo> fetchByTarget(String... values) {
        return fetch(SysMenu.SYS_MENU.TARGET, values);
    }

    /**
     * Fetch records that have <code>icon IN (values)</code>
     */
    public List<SysMenuPojo> fetchByIcon(String... values) {
        return fetch(SysMenu.SYS_MENU.ICON, values);
    }

    /**
     * Fetch records that have <code>sort IN (values)</code>
     */
    public List<SysMenuPojo> fetchBySort(Integer... values) {
        return fetch(SysMenu.SYS_MENU.SORT, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<SysMenuPojo> fetchByStatus(SysMenuStatus... values) {
        return fetch(SysMenu.SYS_MENU.STATUS, values);
    }

    /**
     * Fetch records that have <code>permission IN (values)</code>
     */
    public List<SysMenuPojo> fetchByPermission(String... values) {
        return fetch(SysMenu.SYS_MENU.PERMISSION, values);
    }

    /**
     * Fetch records that have <code>create_at IN (values)</code>
     */
    public List<SysMenuPojo> fetchByCreateAt(Timestamp... values) {
        return fetch(SysMenu.SYS_MENU.CREATE_AT, values);
    }

    /**
     * Fetch records that have <code>update_at IN (values)</code>
     */
    public List<SysMenuPojo> fetchByUpdateAt(Timestamp... values) {
        return fetch(SysMenu.SYS_MENU.UPDATE_AT, values);
    }

    /**
     * Fetch records that have <code>remarks IN (values)</code>
     */
    public List<SysMenuPojo> fetchByRemarks(String... values) {
        return fetch(SysMenu.SYS_MENU.REMARKS, values);
    }

    /**
     * Fetch records that have <code>del_flag IN (values)</code>
     */
    public List<SysMenuPojo> fetchByDelFlag(Boolean... values) {
        return fetch(SysMenu.SYS_MENU.DEL_FLAG, values);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<SysMenuPojo> fetchByVersion(Long... values) {
        return fetch(SysMenu.SYS_MENU.VERSION, values);
    }
}
