/*
 * This file is generated by jOOQ.
*/
package com.dreamer.domain.tables.daos;


import com.dreamer.domain.tables.SysRoleMenu;
import com.dreamer.domain.tables.pojos.SysRoleMenuPojo;
import com.dreamer.domain.tables.records.SysRoleMenuRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record3;
import org.jooq.impl.DAOImpl;


/**
 * 角色-菜单
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRoleMenuDao extends DAOImpl<SysRoleMenuRecord, SysRoleMenuPojo, Record3<Long, Long, Long>> {

    /**
     * Create a new SysRoleMenuDao without any configuration
     */
    public SysRoleMenuDao() {
        super(SysRoleMenu.SYS_ROLE_MENU, SysRoleMenuPojo.class);
    }

    /**
     * Create a new SysRoleMenuDao with an attached configuration
     */
    public SysRoleMenuDao(Configuration configuration) {
        super(SysRoleMenu.SYS_ROLE_MENU, SysRoleMenuPojo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record3<Long, Long, Long> getId(SysRoleMenuPojo object) {
        return compositeKeyRecord(object.getId(), object.getSysRoleId(), object.getSysMenuId());
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<SysRoleMenuPojo> fetchById(Long... values) {
        return fetch(SysRoleMenu.SYS_ROLE_MENU.ID, values);
    }

    /**
     * Fetch records that have <code>sys_role_id IN (values)</code>
     */
    public List<SysRoleMenuPojo> fetchBySysRoleId(Long... values) {
        return fetch(SysRoleMenu.SYS_ROLE_MENU.SYS_ROLE_ID, values);
    }

    /**
     * Fetch records that have <code>sys_menu_id IN (values)</code>
     */
    public List<SysRoleMenuPojo> fetchBySysMenuId(Long... values) {
        return fetch(SysRoleMenu.SYS_ROLE_MENU.SYS_MENU_ID, values);
    }
}
