/*
 * This file is generated by jOOQ.
*/
package com.dreamer.domain.tables.daos;


import com.dreamer.domain.enums.SysUserStatus;
import com.dreamer.domain.tables.SysUser;
import com.dreamer.domain.tables.pojos.SysUserPojo;
import com.dreamer.domain.tables.records.SysUserRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 用户表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserDao extends DAOImpl<SysUserRecord, SysUserPojo, Long> {

    /**
     * Create a new SysUserDao without any configuration
     */
    public SysUserDao() {
        super(SysUser.SYS_USER, SysUserPojo.class);
    }

    /**
     * Create a new SysUserDao with an attached configuration
     */
    public SysUserDao(Configuration configuration) {
        super(SysUser.SYS_USER, SysUserPojo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(SysUserPojo object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<SysUserPojo> fetchById(Long... values) {
        return fetch(SysUser.SYS_USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public SysUserPojo fetchOneById(Long value) {
        return fetchOne(SysUser.SYS_USER.ID, value);
    }

    /**
     * Fetch records that have <code>login_name IN (values)</code>
     */
    public List<SysUserPojo> fetchByLoginName(String... values) {
        return fetch(SysUser.SYS_USER.LOGIN_NAME, values);
    }

    /**
     * Fetch a unique record that has <code>login_name = value</code>
     */
    public SysUserPojo fetchOneByLoginName(String value) {
        return fetchOne(SysUser.SYS_USER.LOGIN_NAME, value);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<SysUserPojo> fetchByPassword(String... values) {
        return fetch(SysUser.SYS_USER.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>no IN (values)</code>
     */
    public List<SysUserPojo> fetchByNo(String... values) {
        return fetch(SysUser.SYS_USER.NO, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<SysUserPojo> fetchByName(String... values) {
        return fetch(SysUser.SYS_USER.NAME, values);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<SysUserPojo> fetchByEmail(String... values) {
        return fetch(SysUser.SYS_USER.EMAIL, values);
    }

    /**
     * Fetch records that have <code>phone IN (values)</code>
     */
    public List<SysUserPojo> fetchByPhone(String... values) {
        return fetch(SysUser.SYS_USER.PHONE, values);
    }

    /**
     * Fetch records that have <code>mobile IN (values)</code>
     */
    public List<SysUserPojo> fetchByMobile(String... values) {
        return fetch(SysUser.SYS_USER.MOBILE, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<SysUserPojo> fetchByStatus(SysUserStatus... values) {
        return fetch(SysUser.SYS_USER.STATUS, values);
    }

    /**
     * Fetch records that have <code>login_ip IN (values)</code>
     */
    public List<SysUserPojo> fetchByLoginIp(String... values) {
        return fetch(SysUser.SYS_USER.LOGIN_IP, values);
    }

    /**
     * Fetch records that have <code>login_time IN (values)</code>
     */
    public List<SysUserPojo> fetchByLoginTime(Timestamp... values) {
        return fetch(SysUser.SYS_USER.LOGIN_TIME, values);
    }

    /**
     * Fetch records that have <code>avatars IN (values)</code>
     */
    public List<SysUserPojo> fetchByAvatars(String... values) {
        return fetch(SysUser.SYS_USER.AVATARS, values);
    }

    /**
     * Fetch records that have <code>create_at IN (values)</code>
     */
    public List<SysUserPojo> fetchByCreateAt(Timestamp... values) {
        return fetch(SysUser.SYS_USER.CREATE_AT, values);
    }

    /**
     * Fetch records that have <code>update_at IN (values)</code>
     */
    public List<SysUserPojo> fetchByUpdateAt(Timestamp... values) {
        return fetch(SysUser.SYS_USER.UPDATE_AT, values);
    }

    /**
     * Fetch records that have <code>remarks IN (values)</code>
     */
    public List<SysUserPojo> fetchByRemarks(String... values) {
        return fetch(SysUser.SYS_USER.REMARKS, values);
    }

    /**
     * Fetch records that have <code>del_flag IN (values)</code>
     */
    public List<SysUserPojo> fetchByDelFlag(Boolean... values) {
        return fetch(SysUser.SYS_USER.DEL_FLAG, values);
    }
}
