/*
 * This file is generated by jOOQ.
*/
package com.dreamer.domain.tables.records;


import com.dreamer.domain.tables.SysUserRole;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户-角色
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserRoleRecord extends UpdatableRecordImpl<SysUserRoleRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = 1608764034;

    /**
     * Setter for <code>jw.sys_user_role.id</code>.
     */
    public SysUserRoleRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>jw.sys_user_role.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>jw.sys_user_role.sys_user_id</code>. 用户编号
     */
    public SysUserRoleRecord setSysUserId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>jw.sys_user_role.sys_user_id</code>. 用户编号
     */
    public Long getSysUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>jw.sys_user_role.sys_role_id</code>. 角色编号
     */
    public SysUserRoleRecord setSysRoleId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>jw.sys_user_role.sys_role_id</code>. 角色编号
     */
    public Long getSysRoleId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<Long, Long, Long> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return SysUserRole.SYS_USER_ROLE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return SysUserRole.SYS_USER_ROLE.SYS_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return SysUserRole.SYS_USER_ROLE.SYS_ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getSysUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getSysRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRoleRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRoleRecord value2(Long value) {
        setSysUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRoleRecord value3(Long value) {
        setSysRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRoleRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysUserRoleRecord
     */
    public SysUserRoleRecord() {
        super(SysUserRole.SYS_USER_ROLE);
    }

    /**
     * Create a detached, initialised SysUserRoleRecord
     */
    public SysUserRoleRecord(Long id, Long sysUserId, Long sysRoleId) {
        super(SysUserRole.SYS_USER_ROLE);

        set(0, id);
        set(1, sysUserId);
        set(2, sysRoleId);
    }
}
