/*
 * This file is generated by jOOQ.
*/
package com.dreamer.domain.tables.records;


import com.dreamer.domain.tables.WcSessionToken;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * 微信会话token表
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class WcSessionTokenRecord extends UpdatableRecordImpl<WcSessionTokenRecord> implements Record5<Long, String, String, String, Timestamp> {

    private static final long serialVersionUID = 1014772481;

    /**
     * Create a detached WcSessionTokenRecord
     */
    public WcSessionTokenRecord() {
        super(WcSessionToken.WC_SESSION_TOKEN);
    }

    /**
     * Create a detached, initialised WcSessionTokenRecord
     */
    public WcSessionTokenRecord(Long id, String sessionToken, String openId, String sessionKey, Timestamp createTime) {
        super(WcSessionToken.WC_SESSION_TOKEN);

        set(0, id);
        set(1, sessionToken);
        set(2, openId);
        set(3, sessionKey);
        set(4, createTime);
    }

    /**
     * Getter for <code>dreamer.wc_session_token.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>dreamer.wc_session_token.id</code>. 主键
     */
    public WcSessionTokenRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>dreamer.wc_session_token.session_token</code>. 平台会话token
     */
    public String getSessionToken() {
        return (String) get(1);
    }

    /**
     * Setter for <code>dreamer.wc_session_token.session_token</code>. 平台会话token
     */
    public WcSessionTokenRecord setSessionToken(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>dreamer.wc_session_token.open_id</code>. 微信用户唯一标识
     */
    public String getOpenId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>dreamer.wc_session_token.open_id</code>. 微信用户唯一标识
     */
    public WcSessionTokenRecord setOpenId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>dreamer.wc_session_token.session_key</code>. 微信会话密钥
     */
    public String getSessionKey() {
        return (String) get(3);
    }

    /**
     * Setter for <code>dreamer.wc_session_token.session_key</code>. 微信会话密钥
     */
    public WcSessionTokenRecord setSessionKey(String value) {
        set(3, value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>dreamer.wc_session_token.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>dreamer.wc_session_token.create_time</code>. 创建时间
     */
    public WcSessionTokenRecord setCreateTime(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, String, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, String, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return WcSessionToken.WC_SESSION_TOKEN.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return WcSessionToken.WC_SESSION_TOKEN.SESSION_TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return WcSessionToken.WC_SESSION_TOKEN.OPEN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return WcSessionToken.WC_SESSION_TOKEN.SESSION_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return WcSessionToken.WC_SESSION_TOKEN.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSessionToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOpenId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSessionKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WcSessionTokenRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WcSessionTokenRecord value2(String value) {
        setSessionToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WcSessionTokenRecord value3(String value) {
        setOpenId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WcSessionTokenRecord value4(String value) {
        setSessionKey(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public WcSessionTokenRecord value5(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WcSessionTokenRecord values(Long value1, String value2, String value3, String value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }
}
