/*
 * This file is generated by jOOQ.
*/
package com.dreamer.admin.domain.tables;


import com.dreamer.admin.domain.Dreamer;
import com.dreamer.admin.domain.Keys;
import com.dreamer.admin.domain.tables.records.CstCourseCatalogRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class CstCourseCatalog extends TableImpl<CstCourseCatalogRecord> {

    /**
     * The reference instance of <code>dreamer.cst_course_catalog</code>
     */
    public static final CstCourseCatalog CST_COURSE_CATALOG = new CstCourseCatalog();
    private static final long serialVersionUID = 1361044633;
    /**
     * The column <code>dreamer.cst_course_catalog.id</code>. 主键
     */
    public final TableField<CstCourseCatalogRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "主键");
    /**
     * The column <code>dreamer.cst_course_catalog.parent_id</code>. 父级id
     */
    public final TableField<CstCourseCatalogRecord, Long> PARENT_ID = createField("parent_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "父级id");
    /**
     * The column <code>dreamer.cst_course_catalog.label</code>. 标签
     */
    public final TableField<CstCourseCatalogRecord, String> LABEL = createField("label", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "标签");
    /**
     * The column <code>dreamer.cst_course_catalog.create_at</code>. 创建时间
     */
    public final TableField<CstCourseCatalogRecord, Timestamp> CREATE_AT = createField("create_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");
    /**
     * The column <code>dreamer.cst_course_catalog.update_at</code>. 更新时间
     */
    public final TableField<CstCourseCatalogRecord, Timestamp> UPDATE_AT = createField("update_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "更新时间");
    /**
     * The column <code>dreamer.cst_course_catalog.remark</code>. 备注信息
     */
    public final TableField<CstCourseCatalogRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "备注信息");
    /**
     * The column <code>dreamer.cst_course_catalog.del_flag</code>. 删除标志
     */
    public final TableField<CstCourseCatalogRecord, Boolean> DEL_FLAG = createField("del_flag", org.jooq.impl.SQLDataType.BIT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("b'0'", org.jooq.impl.SQLDataType.BIT)), this, "删除标志");
    /**
     * The column <code>dreamer.cst_course_catalog.version</code>.
     */
    public final TableField<CstCourseCatalogRecord, Long> VERSION = createField("version", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * Create a <code>dreamer.cst_course_catalog</code> table reference
     */
    public CstCourseCatalog() {
        this("cst_course_catalog", null);
    }

    /**
     * Create an aliased <code>dreamer.cst_course_catalog</code> table reference
     */
    public CstCourseCatalog(String alias) {
        this(alias, CST_COURSE_CATALOG);
    }

    private CstCourseCatalog(String alias, Table<CstCourseCatalogRecord> aliased) {
        this(alias, aliased, null);
    }

    private CstCourseCatalog(String alias, Table<CstCourseCatalogRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CstCourseCatalogRecord> getRecordType() {
        return CstCourseCatalogRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dreamer.DREAMER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CstCourseCatalogRecord, Long> getIdentity() {
        return Keys.IDENTITY_CST_COURSE_CATALOG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CstCourseCatalogRecord> getPrimaryKey() {
        return Keys.KEY_CST_COURSE_CATALOG_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CstCourseCatalogRecord>> getKeys() {
        return Arrays.<UniqueKey<CstCourseCatalogRecord>>asList(Keys.KEY_CST_COURSE_CATALOG_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TableField<CstCourseCatalogRecord, Long> getRecordVersion() {
        return VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CstCourseCatalog as(String alias) {
        return new CstCourseCatalog(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CstCourseCatalog rename(String name) {
        return new CstCourseCatalog(name, null);
    }
}
