/*
 * This file is generated by jOOQ.
*/
package com.dreamer.admin.domain.tables;


import com.dreamer.admin.domain.Dreamer;
import com.dreamer.admin.domain.Keys;
import com.dreamer.admin.domain.enums.OgnCourseCourseStatus;
import com.dreamer.admin.domain.enums.OgnCoursePeriodType;
import com.dreamer.admin.domain.tables.records.OgnCourseRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class OgnCourse extends TableImpl<OgnCourseRecord> {

    /**
     * The reference instance of <code>dreamer.ogn_course</code>
     */
    public static final OgnCourse OGN_COURSE = new OgnCourse();
    private static final long serialVersionUID = 1481705307;
    /**
     * The column <code>dreamer.ogn_course.id</code>. 主键
     */
    public final TableField<OgnCourseRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "主键");
    /**
     * The column <code>dreamer.ogn_course.ogn_id</code>. 机构ID
     */
    public final TableField<OgnCourseRecord, Long> OGN_ID = createField("ogn_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "机构ID");
    /**
     * The column <code>dreamer.ogn_course.course_catalog_id</code>. 课程目录ID
     */
    public final TableField<OgnCourseRecord, Long> COURSE_CATALOG_ID = createField("course_catalog_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "课程目录ID");
    /**
     * The column <code>dreamer.ogn_course.course_name</code>. 课名
     */
    public final TableField<OgnCourseRecord, String> COURSE_NAME = createField("course_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "课名");
    /**
     * The column <code>dreamer.ogn_course.course_title</code>. 课标题
     */
    public final TableField<OgnCourseRecord, String> COURSE_TITLE = createField("course_title", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "课标题");
    /**
     * The column <code>dreamer.ogn_course.course_short_introduce</code>. 课简介
     */
    public final TableField<OgnCourseRecord, String> COURSE_SHORT_INTRODUCE = createField("course_short_introduce", org.jooq.impl.SQLDataType.CLOB, this, "课简介");
    /**
     * The column <code>dreamer.ogn_course.course_address</code>. 上课地址
     */
    public final TableField<OgnCourseRecord, String> COURSE_ADDRESS = createField("course_address", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "上课地址");
    /**
     * The column <code>dreamer.ogn_course.period_num</code>. 周期内数量
     */
    public final TableField<OgnCourseRecord, Integer> PERIOD_NUM = createField("period_num", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "周期内数量");
    /**
     * The column <code>dreamer.ogn_course.period_type</code>. 周期类型：日；周；月；年
     */
    public final TableField<OgnCourseRecord, OgnCoursePeriodType> PERIOD_TYPE = createField("period_type", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.dreamer.admin.domain.enums.OgnCoursePeriodType.class), this, "周期类型：日；周；月；年");
    /**
     * The column <code>dreamer.ogn_course.course_status</code>. 课状态：已保存；已审核；已上线；已下线；
     */
    public final TableField<OgnCourseRecord, OgnCourseCourseStatus> COURSE_STATUS = createField("course_status", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.dreamer.admin.domain.enums.OgnCourseCourseStatus.class), this, "课状态：已保存；已审核；已上线；已下线；");
    /**
     * The column <code>dreamer.ogn_course.enter_age_upper</code>. 报名年龄上限
     */
    public final TableField<OgnCourseRecord, Integer> ENTER_AGE_UPPER = createField("enter_age_upper", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "报名年龄上限");
    /**
     * The column <code>dreamer.ogn_course.enter_age_lower</code>. 报名年龄下限
     */
    public final TableField<OgnCourseRecord, Integer> ENTER_AGE_LOWER = createField("enter_age_lower", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "报名年龄下限");
    /**
     * The column <code>dreamer.ogn_course.online_time</code>. 上线时间
     */
    public final TableField<OgnCourseRecord, Timestamp> ONLINE_TIME = createField("online_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "上线时间");
    /**
     * The column <code>dreamer.ogn_course.enter_time_start</code>. 报名开始时间
     */
    public final TableField<OgnCourseRecord, Timestamp> ENTER_TIME_START = createField("enter_time_start", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "报名开始时间");
    /**
     * The column <code>dreamer.ogn_course.enter_time_end</code>. 报名结束时间
     */
    public final TableField<OgnCourseRecord, Timestamp> ENTER_TIME_END = createField("enter_time_end", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "报名结束时间");
    /**
     * The column <code>dreamer.ogn_course.remarks</code>. 备注信息
     */
    public final TableField<OgnCourseRecord, String> REMARKS = createField("remarks", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "备注信息");
    /**
     * The column <code>dreamer.ogn_course.create_at</code>. 创建时间
     */
    public final TableField<OgnCourseRecord, Timestamp> CREATE_AT = createField("create_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");
    /**
     * The column <code>dreamer.ogn_course.update_at</code>. 更新时间
     */
    public final TableField<OgnCourseRecord, Timestamp> UPDATE_AT = createField("update_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "更新时间");
    /**
     * The column <code>dreamer.ogn_course.del_flag</code>. 删除标志
     */
    public final TableField<OgnCourseRecord, Boolean> DEL_FLAG = createField("del_flag", org.jooq.impl.SQLDataType.BIT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("b'0'", org.jooq.impl.SQLDataType.BIT)), this, "删除标志");
    /**
     * The column <code>dreamer.ogn_course.version</code>.
     */
    public final TableField<OgnCourseRecord, Long> VERSION = createField("version", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>dreamer.ogn_course</code> table reference
     */
    public OgnCourse() {
        this("ogn_course", null);
    }

    /**
     * Create an aliased <code>dreamer.ogn_course</code> table reference
     */
    public OgnCourse(String alias) {
        this(alias, OGN_COURSE);
    }

    private OgnCourse(String alias, Table<OgnCourseRecord> aliased) {
        this(alias, aliased, null);
    }

    private OgnCourse(String alias, Table<OgnCourseRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OgnCourseRecord> getRecordType() {
        return OgnCourseRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dreamer.DREAMER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OgnCourseRecord> getPrimaryKey() {
        return Keys.KEY_OGN_COURSE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OgnCourseRecord>> getKeys() {
        return Arrays.<UniqueKey<OgnCourseRecord>>asList(Keys.KEY_OGN_COURSE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TableField<OgnCourseRecord, Long> getRecordVersion() {
        return VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OgnCourse as(String alias) {
        return new OgnCourse(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OgnCourse rename(String name) {
        return new OgnCourse(name, null);
    }
}
