/*
 * This file is generated by jOOQ.
*/
package com.dreamer.admin.domain.tables;


import com.dreamer.admin.domain.Dreamer;
import com.dreamer.admin.domain.Keys;
import com.dreamer.admin.domain.enums.SysMenuStatus;
import com.dreamer.admin.domain.enums.SysMenuType;
import com.dreamer.admin.domain.tables.records.SysMenuRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * 菜单表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysMenu extends TableImpl<SysMenuRecord> {

    /**
     * The reference instance of <code>dreamer.sys_menu</code>
     */
    public static final SysMenu SYS_MENU = new SysMenu();
    private static final long serialVersionUID = -1769225620;
    /**
     * The column <code>dreamer.sys_menu.id</code>. 编号
     */
    public final TableField<SysMenuRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "编号");
    /**
     * The column <code>dreamer.sys_menu.parent_id</code>. 父级编号
     */
    public final TableField<SysMenuRecord, Long> PARENT_ID = createField("parent_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "父级编号");
    /**
     * The column <code>dreamer.sys_menu.type</code>. 类型一级菜单，页面，功能按钮
     */
    public final TableField<SysMenuRecord, SysMenuType> TYPE = createField("type", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.dreamer.admin.domain.enums.SysMenuType.class), this, "类型一级菜单，页面，功能按钮");
    /**
     * The column <code>dreamer.sys_menu.name</code>. 菜单名称
     */
    public final TableField<SysMenuRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "菜单名称");
    /**
     * The column <code>dreamer.sys_menu.href</code>. 链接
     */
    public final TableField<SysMenuRecord, String> HREF = createField("href", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "链接");
    /**
     * The column <code>dreamer.sys_menu.target</code>. 目标
     */
    public final TableField<SysMenuRecord, String> TARGET = createField("target", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "目标");
    /**
     * The column <code>dreamer.sys_menu.icon</code>. 图标
     */
    public final TableField<SysMenuRecord, String> ICON = createField("icon", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "图标");
    /**
     * The column <code>dreamer.sys_menu.sort</code>. 排序（升序）
     */
    public final TableField<SysMenuRecord, Integer> SORT = createField("sort", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "排序（升序）");
    /**
     * The column <code>dreamer.sys_menu.status</code>. 状态
     */
    public final TableField<SysMenuRecord, SysMenuStatus> STATUS = createField("status", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.dreamer.admin.domain.enums.SysMenuStatus.class), this, "状态");
    /**
     * The column <code>dreamer.sys_menu.permission</code>. 权限标识
     */
    public final TableField<SysMenuRecord, String> PERMISSION = createField("permission", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "权限标识");
    /**
     * The column <code>dreamer.sys_menu.create_at</code>. 创建时间
     */
    public final TableField<SysMenuRecord, Timestamp> CREATE_AT = createField("create_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");
    /**
     * The column <code>dreamer.sys_menu.update_at</code>. 更新时间
     */
    public final TableField<SysMenuRecord, Timestamp> UPDATE_AT = createField("update_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "更新时间");
    /**
     * The column <code>dreamer.sys_menu.remarks</code>. 备注信息
     */
    public final TableField<SysMenuRecord, String> REMARKS = createField("remarks", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "备注信息");
    /**
     * The column <code>dreamer.sys_menu.del_flag</code>. 删除标记
     */
    public final TableField<SysMenuRecord, Boolean> DEL_FLAG = createField("del_flag", org.jooq.impl.SQLDataType.BIT.nullable(false), this, "删除标记");
    /**
     * The column <code>dreamer.sys_menu.version</code>.
     */
    public final TableField<SysMenuRecord, Long> VERSION = createField("version", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>dreamer.sys_menu</code> table reference
     */
    public SysMenu() {
        this("sys_menu", null);
    }

    /**
     * Create an aliased <code>dreamer.sys_menu</code> table reference
     */
    public SysMenu(String alias) {
        this(alias, SYS_MENU);
    }

    private SysMenu(String alias, Table<SysMenuRecord> aliased) {
        this(alias, aliased, null);
    }

    private SysMenu(String alias, Table<SysMenuRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "菜单表");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysMenuRecord> getRecordType() {
        return SysMenuRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dreamer.DREAMER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SysMenuRecord, Long> getIdentity() {
        return Keys.IDENTITY_SYS_MENU;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SysMenuRecord> getPrimaryKey() {
        return Keys.KEY_SYS_MENU_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SysMenuRecord>> getKeys() {
        return Arrays.<UniqueKey<SysMenuRecord>>asList(Keys.KEY_SYS_MENU_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TableField<SysMenuRecord, Long> getRecordVersion() {
        return VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenu as(String alias) {
        return new SysMenu(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SysMenu rename(String name) {
        return new SysMenu(name, null);
    }
}
